//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC.MMCService.EmailRecordAttachmentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailRecord", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class EmailRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EmailRecDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecBody {
            get {
                return this.EmRecBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecBodyField, value) != true)) {
                    this.EmRecBodyField = value;
                    this.RaisePropertyChanged("EmRecBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecCC {
            get {
                return this.EmRecCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecCCField, value) != true)) {
                    this.EmRecCCField = value;
                    this.RaisePropertyChanged("EmRecCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecSubject {
            get {
                return this.EmRecSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecSubjectField, value) != true)) {
                    this.EmRecSubjectField = value;
                    this.RaisePropertyChanged("EmRecSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecTo {
            get {
                return this.EmRecToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecToField, value) != true)) {
                    this.EmRecToField = value;
                    this.RaisePropertyChanged("EmRecTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EmailRecDate {
            get {
                return this.EmailRecDateField;
            }
            set {
                if ((this.EmailRecDateField.Equals(value) != true)) {
                    this.EmailRecDateField = value;
                    this.RaisePropertyChanged("EmailRecDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailRecordId {
            get {
                return this.EmailRecordIdField;
            }
            set {
                if ((this.EmailRecordIdField.Equals(value) != true)) {
                    this.EmailRecordIdField = value;
                    this.RaisePropertyChanged("EmailRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailRecordAttachment", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class EmailRecordAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmRecToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailAttachmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailRecordIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentPath {
            get {
                return this.DocumentPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentPathField, value) != true)) {
                    this.DocumentPathField = value;
                    this.RaisePropertyChanged("DocumentPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecBody {
            get {
                return this.EmRecBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecBodyField, value) != true)) {
                    this.EmRecBodyField = value;
                    this.RaisePropertyChanged("EmRecBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecCC {
            get {
                return this.EmRecCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecCCField, value) != true)) {
                    this.EmRecCCField = value;
                    this.RaisePropertyChanged("EmRecCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecSubject {
            get {
                return this.EmRecSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecSubjectField, value) != true)) {
                    this.EmRecSubjectField = value;
                    this.RaisePropertyChanged("EmRecSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmRecTo {
            get {
                return this.EmRecToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmRecToField, value) != true)) {
                    this.EmRecToField = value;
                    this.RaisePropertyChanged("EmRecTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailAttachmentId {
            get {
                return this.EmailAttachmentIdField;
            }
            set {
                if ((this.EmailAttachmentIdField.Equals(value) != true)) {
                    this.EmailAttachmentIdField = value;
                    this.RaisePropertyChanged("EmailAttachmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailRecordId {
            get {
                return this.EmailRecordIdField;
            }
            set {
                if ((this.EmailRecordIdField.Equals(value) != true)) {
                    this.EmailRecordIdField = value;
                    this.RaisePropertyChanged("EmailRecordId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedEmailRecordAttachment", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedEmailRecordAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MMC.MMCService.EmailRecordAttachmentService.EmailRecordAttachment[] EmailRecordAttachmentDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MMC.MMCService.EmailRecordAttachmentService.EmailRecordAttachment[] EmailRecordAttachmentDetails {
            get {
                return this.EmailRecordAttachmentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailRecordAttachmentDetailsField, value) != true)) {
                    this.EmailRecordAttachmentDetailsField = value;
                    this.RaisePropertyChanged("EmailRecordAttachmentDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MMCService.EmailRecordAttachmentService.IEmailRecordAttachmentService")]
    public interface IEmailRecordAttachmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecord", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecordResponse")]
        int addEmailRecord(MMC.MMCService.EmailRecordAttachmentService.EmailRecord _emailRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecord", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecordResponse")]
        System.Threading.Tasks.Task<int> addEmailRecordAsync(MMC.MMCService.EmailRecordAttachmentService.EmailRecord _emailRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecordAttachment", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecordAttachmentResponse" +
            "")]
        int addEmailRecordAttachment(MMC.MMCService.EmailRecordAttachmentService.EmailRecordAttachment _emailRecordAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecordAttachment", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/addEmailRecordAttachmentResponse" +
            "")]
        System.Threading.Tasks.Task<int> addEmailRecordAttachmentAsync(MMC.MMCService.EmailRecordAttachmentService.EmailRecordAttachment _emailRecordAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/getEmailRecordAttachmentByEmailR" +
            "ecordId", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/getEmailRecordAttachmentByEmailR" +
            "ecordIdResponse")]
        MMC.MMCService.EmailRecordAttachmentService.PagedEmailRecordAttachment getEmailRecordAttachmentByEmailRecordId(int emailRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/getEmailRecordAttachmentByEmailR" +
            "ecordId", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/getEmailRecordAttachmentByEmailR" +
            "ecordIdResponse")]
        System.Threading.Tasks.Task<MMC.MMCService.EmailRecordAttachmentService.PagedEmailRecordAttachment> getEmailRecordAttachmentByEmailRecordIdAsync(int emailRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFAReferralID", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFAReferralIDResponse")]
        void AddEmailRecordAndRFARequestLinkByRFAReferralID(int RFAReferralID, int EmailRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFAReferralID", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFAReferralIDResponse")]
        System.Threading.Tasks.Task AddEmailRecordAndRFARequestLinkByRFAReferralIDAsync(int RFAReferralID, int EmailRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFITimeExtension", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFITimeExtensionResponse")]
        void AddEmailRecordAndRFARequestLinkByRFITimeExtension(int RFAReferralID, int RFAReferralFileID, int EmailRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFITimeExtension", ReplyAction="http://tempuri.org/IEmailRecordAttachmentService/AddEmailRecordAndRFARequestLinkB" +
            "yRFITimeExtensionResponse")]
        System.Threading.Tasks.Task AddEmailRecordAndRFARequestLinkByRFITimeExtensionAsync(int RFAReferralID, int RFAReferralFileID, int EmailRecordId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailRecordAttachmentServiceChannel : MMC.MMCService.EmailRecordAttachmentService.IEmailRecordAttachmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailRecordAttachmentServiceClient : System.ServiceModel.ClientBase<MMC.MMCService.EmailRecordAttachmentService.IEmailRecordAttachmentService>, MMC.MMCService.EmailRecordAttachmentService.IEmailRecordAttachmentService {
        
        public EmailRecordAttachmentServiceClient() {
        }
        
        public EmailRecordAttachmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailRecordAttachmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailRecordAttachmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailRecordAttachmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addEmailRecord(MMC.MMCService.EmailRecordAttachmentService.EmailRecord _emailRecord) {
            return base.Channel.addEmailRecord(_emailRecord);
        }
        
        public System.Threading.Tasks.Task<int> addEmailRecordAsync(MMC.MMCService.EmailRecordAttachmentService.EmailRecord _emailRecord) {
            return base.Channel.addEmailRecordAsync(_emailRecord);
        }
        
        public int addEmailRecordAttachment(MMC.MMCService.EmailRecordAttachmentService.EmailRecordAttachment _emailRecordAttachment) {
            return base.Channel.addEmailRecordAttachment(_emailRecordAttachment);
        }
        
        public System.Threading.Tasks.Task<int> addEmailRecordAttachmentAsync(MMC.MMCService.EmailRecordAttachmentService.EmailRecordAttachment _emailRecordAttachment) {
            return base.Channel.addEmailRecordAttachmentAsync(_emailRecordAttachment);
        }
        
        public MMC.MMCService.EmailRecordAttachmentService.PagedEmailRecordAttachment getEmailRecordAttachmentByEmailRecordId(int emailRecordId) {
            return base.Channel.getEmailRecordAttachmentByEmailRecordId(emailRecordId);
        }
        
        public System.Threading.Tasks.Task<MMC.MMCService.EmailRecordAttachmentService.PagedEmailRecordAttachment> getEmailRecordAttachmentByEmailRecordIdAsync(int emailRecordId) {
            return base.Channel.getEmailRecordAttachmentByEmailRecordIdAsync(emailRecordId);
        }
        
        public void AddEmailRecordAndRFARequestLinkByRFAReferralID(int RFAReferralID, int EmailRecordId) {
            base.Channel.AddEmailRecordAndRFARequestLinkByRFAReferralID(RFAReferralID, EmailRecordId);
        }
        
        public System.Threading.Tasks.Task AddEmailRecordAndRFARequestLinkByRFAReferralIDAsync(int RFAReferralID, int EmailRecordId) {
            return base.Channel.AddEmailRecordAndRFARequestLinkByRFAReferralIDAsync(RFAReferralID, EmailRecordId);
        }
        
        public void AddEmailRecordAndRFARequestLinkByRFITimeExtension(int RFAReferralID, int RFAReferralFileID, int EmailRecordId) {
            base.Channel.AddEmailRecordAndRFARequestLinkByRFITimeExtension(RFAReferralID, RFAReferralFileID, EmailRecordId);
        }
        
        public System.Threading.Tasks.Task AddEmailRecordAndRFARequestLinkByRFITimeExtensionAsync(int RFAReferralID, int RFAReferralFileID, int EmailRecordId) {
            return base.Channel.AddEmailRecordAndRFARequestLinkByRFITimeExtensionAsync(RFAReferralID, RFAReferralFileID, EmailRecordId);
        }
    }
}
