//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC.MMCService.BillingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedBilling", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedBilling : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MMC.MMCService.BillingService.Billing[] BillingDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MMC.MMCService.BillingService.Billing[] BillingDetails {
            get {
                return this.BillingDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingDetailsField, value) != true)) {
                    this.BillingDetailsField = value;
                    this.RaisePropertyChanged("BillingDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Billing", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class Billing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BillingTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientBillingRateTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DecisionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientClaimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFAReferralIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingDeferralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFARequestBillingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingMDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingSpecialityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFARequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFARequestedTreatmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BillingTotal {
            get {
                return this.BillingTotalField;
            }
            set {
                if ((this.BillingTotalField.Equals(value) != true)) {
                    this.BillingTotalField = value;
                    this.RaisePropertyChanged("BillingTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientBillingRateTypeID {
            get {
                return this.ClientBillingRateTypeIDField;
            }
            set {
                if ((this.ClientBillingRateTypeIDField.Equals(value) != true)) {
                    this.ClientBillingRateTypeIDField = value;
                    this.RaisePropertyChanged("ClientBillingRateTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DecisionID {
            get {
                return this.DecisionIDField;
            }
            set {
                if ((this.DecisionIDField.Equals(value) != true)) {
                    this.DecisionIDField = value;
                    this.RaisePropertyChanged("DecisionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatClientID {
            get {
                return this.PatClientIDField;
            }
            set {
                if ((this.PatClientIDField.Equals(value) != true)) {
                    this.PatClientIDField = value;
                    this.RaisePropertyChanged("PatClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientClaimID {
            get {
                return this.PatientClaimIDField;
            }
            set {
                if ((this.PatientClaimIDField.Equals(value) != true)) {
                    this.PatientClaimIDField = value;
                    this.RaisePropertyChanged("PatientClaimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientName {
            get {
                return this.PatientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientNameField, value) != true)) {
                    this.PatientNameField = value;
                    this.RaisePropertyChanged("PatientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFAReferralID {
            get {
                return this.RFAReferralIDField;
            }
            set {
                if ((this.RFAReferralIDField.Equals(value) != true)) {
                    this.RFAReferralIDField = value;
                    this.RaisePropertyChanged("RFAReferralID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingAdmin {
            get {
                return this.RFARequestBillingAdminField;
            }
            set {
                if ((this.RFARequestBillingAdminField.Equals(value) != true)) {
                    this.RFARequestBillingAdminField = value;
                    this.RaisePropertyChanged("RFARequestBillingAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingDeferral {
            get {
                return this.RFARequestBillingDeferralField;
            }
            set {
                if ((this.RFARequestBillingDeferralField.Equals(value) != true)) {
                    this.RFARequestBillingDeferralField = value;
                    this.RaisePropertyChanged("RFARequestBillingDeferral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFARequestBillingID {
            get {
                return this.RFARequestBillingIDField;
            }
            set {
                if ((this.RFARequestBillingIDField.Equals(value) != true)) {
                    this.RFARequestBillingIDField = value;
                    this.RaisePropertyChanged("RFARequestBillingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingMD {
            get {
                return this.RFARequestBillingMDField;
            }
            set {
                if ((this.RFARequestBillingMDField.Equals(value) != true)) {
                    this.RFARequestBillingMDField = value;
                    this.RaisePropertyChanged("RFARequestBillingMD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingRN {
            get {
                return this.RFARequestBillingRNField;
            }
            set {
                if ((this.RFARequestBillingRNField.Equals(value) != true)) {
                    this.RFARequestBillingRNField = value;
                    this.RaisePropertyChanged("RFARequestBillingRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingSpeciality {
            get {
                return this.RFARequestBillingSpecialityField;
            }
            set {
                if ((this.RFARequestBillingSpecialityField.Equals(value) != true)) {
                    this.RFARequestBillingSpecialityField = value;
                    this.RaisePropertyChanged("RFARequestBillingSpeciality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFARequestID {
            get {
                return this.RFARequestIDField;
            }
            set {
                if ((this.RFARequestIDField.Equals(value) != true)) {
                    this.RFARequestIDField = value;
                    this.RaisePropertyChanged("RFARequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFARequestedTreatment {
            get {
                return this.RFARequestedTreatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.RFARequestedTreatmentField, value) != true)) {
                    this.RFARequestedTreatmentField = value;
                    this.RaisePropertyChanged("RFARequestedTreatment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RFARequestBilling", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class RFARequestBilling : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingDeferralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFARequestBillingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingMDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RFARequestBillingSpecialityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFARequestIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingAdmin {
            get {
                return this.RFARequestBillingAdminField;
            }
            set {
                if ((this.RFARequestBillingAdminField.Equals(value) != true)) {
                    this.RFARequestBillingAdminField = value;
                    this.RaisePropertyChanged("RFARequestBillingAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingDeferral {
            get {
                return this.RFARequestBillingDeferralField;
            }
            set {
                if ((this.RFARequestBillingDeferralField.Equals(value) != true)) {
                    this.RFARequestBillingDeferralField = value;
                    this.RaisePropertyChanged("RFARequestBillingDeferral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFARequestBillingID {
            get {
                return this.RFARequestBillingIDField;
            }
            set {
                if ((this.RFARequestBillingIDField.Equals(value) != true)) {
                    this.RFARequestBillingIDField = value;
                    this.RaisePropertyChanged("RFARequestBillingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingMD {
            get {
                return this.RFARequestBillingMDField;
            }
            set {
                if ((this.RFARequestBillingMDField.Equals(value) != true)) {
                    this.RFARequestBillingMDField = value;
                    this.RaisePropertyChanged("RFARequestBillingMD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingRN {
            get {
                return this.RFARequestBillingRNField;
            }
            set {
                if ((this.RFARequestBillingRNField.Equals(value) != true)) {
                    this.RFARequestBillingRNField = value;
                    this.RaisePropertyChanged("RFARequestBillingRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RFARequestBillingSpeciality {
            get {
                return this.RFARequestBillingSpecialityField;
            }
            set {
                if ((this.RFARequestBillingSpecialityField.Equals(value) != true)) {
                    this.RFARequestBillingSpecialityField = value;
                    this.RaisePropertyChanged("RFARequestBillingSpeciality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFARequestID {
            get {
                return this.RFARequestIDField;
            }
            set {
                if ((this.RFARequestIDField.Equals(value) != true)) {
                    this.RFARequestIDField = value;
                    this.RaisePropertyChanged("RFARequestID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RFAReferralInvoice", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class RFAReferralInvoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientClaimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFAReferralInvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceFileName {
            get {
                return this.InvoiceFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceFileNameField, value) != true)) {
                    this.InvoiceFileNameField = value;
                    this.RaisePropertyChanged("InvoiceFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientClaimID {
            get {
                return this.PatientClaimIDField;
            }
            set {
                if ((this.PatientClaimIDField.Equals(value) != true)) {
                    this.PatientClaimIDField = value;
                    this.RaisePropertyChanged("PatientClaimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFAReferralInvoiceID {
            get {
                return this.RFAReferralInvoiceIDField;
            }
            set {
                if ((this.RFAReferralInvoiceIDField.Equals(value) != true)) {
                    this.RFAReferralInvoiceIDField = value;
                    this.RaisePropertyChanged("RFAReferralInvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientStatement", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class ClientStatement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientStatementFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientStatementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientStatementNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientStatementFileName {
            get {
                return this.ClientStatementFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientStatementFileNameField, value) != true)) {
                    this.ClientStatementFileNameField = value;
                    this.RaisePropertyChanged("ClientStatementFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientStatementID {
            get {
                return this.ClientStatementIDField;
            }
            set {
                if ((this.ClientStatementIDField.Equals(value) != true)) {
                    this.ClientStatementIDField = value;
                    this.RaisePropertyChanged("ClientStatementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientStatementNumber {
            get {
                return this.ClientStatementNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientStatementNumberField, value) != true)) {
                    this.ClientStatementNumberField = value;
                    this.RaisePropertyChanged("ClientStatementNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedBillingAccountReceivables", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedBillingAccountReceivables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MMC.MMCService.BillingService.BillingAccountReceivables[] AccountReceivableDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MMC.MMCService.BillingService.BillingAccountReceivables[] AccountReceivableDetails {
            get {
                return this.AccountReceivableDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountReceivableDetailsField, value) != true)) {
                    this.AccountReceivableDetailsField = value;
                    this.RaisePropertyChanged("AccountReceivableDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingAccountReceivables", Namespace="http://schemas.datacontract.org/2004/07/MMCService.DTO")]
    [System.SerializableAttribute()]
    public partial class BillingAccountReceivables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientStatementFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClientStatementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientStatementNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientClaimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RFAReferralInvoiceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientStatementFileName {
            get {
                return this.ClientStatementFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientStatementFileNameField, value) != true)) {
                    this.ClientStatementFileNameField = value;
                    this.RaisePropertyChanged("ClientStatementFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClientStatementID {
            get {
                return this.ClientStatementIDField;
            }
            set {
                if ((this.ClientStatementIDField.Equals(value) != true)) {
                    this.ClientStatementIDField = value;
                    this.RaisePropertyChanged("ClientStatementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientStatementNumber {
            get {
                return this.ClientStatementNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientStatementNumberField, value) != true)) {
                    this.ClientStatementNumberField = value;
                    this.RaisePropertyChanged("ClientStatementNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceFileName {
            get {
                return this.InvoiceFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceFileNameField, value) != true)) {
                    this.InvoiceFileNameField = value;
                    this.RaisePropertyChanged("InvoiceFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatClaimNumber {
            get {
                return this.PatClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PatClaimNumberField, value) != true)) {
                    this.PatClaimNumberField = value;
                    this.RaisePropertyChanged("PatClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientClaimID {
            get {
                return this.PatientClaimIDField;
            }
            set {
                if ((this.PatientClaimIDField.Equals(value) != true)) {
                    this.PatientClaimIDField = value;
                    this.RaisePropertyChanged("PatientClaimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((this.PatientIDField.Equals(value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientName {
            get {
                return this.PatientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientNameField, value) != true)) {
                    this.PatientNameField = value;
                    this.RaisePropertyChanged("PatientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RFAReferralInvoiceID {
            get {
                return this.RFAReferralInvoiceIDField;
            }
            set {
                if ((this.RFAReferralInvoiceIDField.Equals(value) != true)) {
                    this.RFAReferralInvoiceIDField = value;
                    this.RaisePropertyChanged("RFAReferralInvoiceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MMCService.BillingService.IBillingService")]
    public interface IBillingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getDetailsForBilling", ReplyAction="http://tempuri.org/IBillingService/getDetailsForBillingResponse")]
        MMC.MMCService.BillingService.PagedBilling getDetailsForBilling(int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getDetailsForBilling", ReplyAction="http://tempuri.org/IBillingService/getDetailsForBillingResponse")]
        System.Threading.Tasks.Task<MMC.MMCService.BillingService.PagedBilling> getDetailsForBillingAsync(int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/updateRFARequestBilling", ReplyAction="http://tempuri.org/IBillingService/updateRFARequestBillingResponse")]
        int updateRFARequestBilling(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/updateRFARequestBilling", ReplyAction="http://tempuri.org/IBillingService/updateRFARequestBillingResponse")]
        System.Threading.Tasks.Task<int> updateRFARequestBillingAsync(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/addRFARequestBilling", ReplyAction="http://tempuri.org/IBillingService/addRFARequestBillingResponse")]
        int addRFARequestBilling(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/addRFARequestBilling", ReplyAction="http://tempuri.org/IBillingService/addRFARequestBillingResponse")]
        System.Threading.Tasks.Task<int> addRFARequestBillingAsync(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getDetailsForBillingByClientName", ReplyAction="http://tempuri.org/IBillingService/getDetailsForBillingByClientNameResponse")]
        MMC.MMCService.BillingService.PagedBilling getDetailsForBillingByClientName(string ClientName, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getDetailsForBillingByClientName", ReplyAction="http://tempuri.org/IBillingService/getDetailsForBillingByClientNameResponse")]
        System.Threading.Tasks.Task<MMC.MMCService.BillingService.PagedBilling> getDetailsForBillingByClientNameAsync(string ClientName, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/addRFAReferralInvoice", ReplyAction="http://tempuri.org/IBillingService/addRFAReferralInvoiceResponse")]
        string addRFAReferralInvoice(MMC.MMCService.BillingService.RFAReferralInvoice _rRFAReferralInvoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/addRFAReferralInvoice", ReplyAction="http://tempuri.org/IBillingService/addRFAReferralInvoiceResponse")]
        System.Threading.Tasks.Task<string> addRFAReferralInvoiceAsync(MMC.MMCService.BillingService.RFAReferralInvoice _rRFAReferralInvoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getInvoiceNumberByClientID", ReplyAction="http://tempuri.org/IBillingService/getInvoiceNumberByClientIDResponse")]
        MMC.MMCService.BillingService.RFAReferralInvoice getInvoiceNumberByClientID(int _ClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getInvoiceNumberByClientID", ReplyAction="http://tempuri.org/IBillingService/getInvoiceNumberByClientIDResponse")]
        System.Threading.Tasks.Task<MMC.MMCService.BillingService.RFAReferralInvoice> getInvoiceNumberByClientIDAsync(int _ClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getInvoiceIDByInvoiceNumber", ReplyAction="http://tempuri.org/IBillingService/getInvoiceIDByInvoiceNumberResponse")]
        int getInvoiceIDByInvoiceNumber(string InvoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getInvoiceIDByInvoiceNumber", ReplyAction="http://tempuri.org/IBillingService/getInvoiceIDByInvoiceNumberResponse")]
        System.Threading.Tasks.Task<int> getInvoiceIDByInvoiceNumberAsync(string InvoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/addClientStatement", ReplyAction="http://tempuri.org/IBillingService/addClientStatementResponse")]
        int addClientStatement(MMC.MMCService.BillingService.ClientStatement _clientStatement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/addClientStatement", ReplyAction="http://tempuri.org/IBillingService/addClientStatementResponse")]
        System.Threading.Tasks.Task<int> addClientStatementAsync(MMC.MMCService.BillingService.ClientStatement _clientStatement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getStatementNumberByClient", ReplyAction="http://tempuri.org/IBillingService/getStatementNumberByClientResponse")]
        MMC.MMCService.BillingService.ClientStatement getStatementNumberByClient(int _clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getStatementNumberByClient", ReplyAction="http://tempuri.org/IBillingService/getStatementNumberByClientResponse")]
        System.Threading.Tasks.Task<MMC.MMCService.BillingService.ClientStatement> getStatementNumberByClientAsync(int _clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getStatementNumberByStatementID", ReplyAction="http://tempuri.org/IBillingService/getStatementNumberByStatementIDResponse")]
        string getStatementNumberByStatementID(int StatementID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getStatementNumberByStatementID", ReplyAction="http://tempuri.org/IBillingService/getStatementNumberByStatementIDResponse")]
        System.Threading.Tasks.Task<string> getStatementNumberByStatementIDAsync(int StatementID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getAccountReceivablesByClientName", ReplyAction="http://tempuri.org/IBillingService/getAccountReceivablesByClientNameResponse")]
        MMC.MMCService.BillingService.PagedBillingAccountReceivables getAccountReceivablesByClientName(string ClientName, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/getAccountReceivablesByClientName", ReplyAction="http://tempuri.org/IBillingService/getAccountReceivablesByClientNameResponse")]
        System.Threading.Tasks.Task<MMC.MMCService.BillingService.PagedBillingAccountReceivables> getAccountReceivablesByClientNameAsync(string ClientName, int skip, int take);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillingServiceChannel : MMC.MMCService.BillingService.IBillingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillingServiceClient : System.ServiceModel.ClientBase<MMC.MMCService.BillingService.IBillingService>, MMC.MMCService.BillingService.IBillingService {
        
        public BillingServiceClient() {
        }
        
        public BillingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MMC.MMCService.BillingService.PagedBilling getDetailsForBilling(int skip, int take) {
            return base.Channel.getDetailsForBilling(skip, take);
        }
        
        public System.Threading.Tasks.Task<MMC.MMCService.BillingService.PagedBilling> getDetailsForBillingAsync(int skip, int take) {
            return base.Channel.getDetailsForBillingAsync(skip, take);
        }
        
        public int updateRFARequestBilling(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling) {
            return base.Channel.updateRFARequestBilling(_rfaRequestBilling);
        }
        
        public System.Threading.Tasks.Task<int> updateRFARequestBillingAsync(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling) {
            return base.Channel.updateRFARequestBillingAsync(_rfaRequestBilling);
        }
        
        public int addRFARequestBilling(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling) {
            return base.Channel.addRFARequestBilling(_rfaRequestBilling);
        }
        
        public System.Threading.Tasks.Task<int> addRFARequestBillingAsync(MMC.MMCService.BillingService.RFARequestBilling _rfaRequestBilling) {
            return base.Channel.addRFARequestBillingAsync(_rfaRequestBilling);
        }
        
        public MMC.MMCService.BillingService.PagedBilling getDetailsForBillingByClientName(string ClientName, int skip, int take) {
            return base.Channel.getDetailsForBillingByClientName(ClientName, skip, take);
        }
        
        public System.Threading.Tasks.Task<MMC.MMCService.BillingService.PagedBilling> getDetailsForBillingByClientNameAsync(string ClientName, int skip, int take) {
            return base.Channel.getDetailsForBillingByClientNameAsync(ClientName, skip, take);
        }
        
        public string addRFAReferralInvoice(MMC.MMCService.BillingService.RFAReferralInvoice _rRFAReferralInvoice) {
            return base.Channel.addRFAReferralInvoice(_rRFAReferralInvoice);
        }
        
        public System.Threading.Tasks.Task<string> addRFAReferralInvoiceAsync(MMC.MMCService.BillingService.RFAReferralInvoice _rRFAReferralInvoice) {
            return base.Channel.addRFAReferralInvoiceAsync(_rRFAReferralInvoice);
        }
        
        public MMC.MMCService.BillingService.RFAReferralInvoice getInvoiceNumberByClientID(int _ClientID) {
            return base.Channel.getInvoiceNumberByClientID(_ClientID);
        }
        
        public System.Threading.Tasks.Task<MMC.MMCService.BillingService.RFAReferralInvoice> getInvoiceNumberByClientIDAsync(int _ClientID) {
            return base.Channel.getInvoiceNumberByClientIDAsync(_ClientID);
        }
        
        public int getInvoiceIDByInvoiceNumber(string InvoiceNumber) {
            return base.Channel.getInvoiceIDByInvoiceNumber(InvoiceNumber);
        }
        
        public System.Threading.Tasks.Task<int> getInvoiceIDByInvoiceNumberAsync(string InvoiceNumber) {
            return base.Channel.getInvoiceIDByInvoiceNumberAsync(InvoiceNumber);
        }
        
        public int addClientStatement(MMC.MMCService.BillingService.ClientStatement _clientStatement) {
            return base.Channel.addClientStatement(_clientStatement);
        }
        
        public System.Threading.Tasks.Task<int> addClientStatementAsync(MMC.MMCService.BillingService.ClientStatement _clientStatement) {
            return base.Channel.addClientStatementAsync(_clientStatement);
        }
        
        public MMC.MMCService.BillingService.ClientStatement getStatementNumberByClient(int _clientID) {
            return base.Channel.getStatementNumberByClient(_clientID);
        }
        
        public System.Threading.Tasks.Task<MMC.MMCService.BillingService.ClientStatement> getStatementNumberByClientAsync(int _clientID) {
            return base.Channel.getStatementNumberByClientAsync(_clientID);
        }
        
        public string getStatementNumberByStatementID(int StatementID) {
            return base.Channel.getStatementNumberByStatementID(StatementID);
        }
        
        public System.Threading.Tasks.Task<string> getStatementNumberByStatementIDAsync(int StatementID) {
            return base.Channel.getStatementNumberByStatementIDAsync(StatementID);
        }
        
        public MMC.MMCService.BillingService.PagedBillingAccountReceivables getAccountReceivablesByClientName(string ClientName, int skip, int take) {
            return base.Channel.getAccountReceivablesByClientName(ClientName, skip, take);
        }
        
        public System.Threading.Tasks.Task<MMC.MMCService.BillingService.PagedBillingAccountReceivables> getAccountReceivablesByClientNameAsync(string ClientName, int skip, int take) {
            return base.Channel.getAccountReceivablesByClientNameAsync(ClientName, skip, take);
        }
    }
}
